// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// IngredientsColumns holds the columns for the "ingredients" table.
	IngredientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "title", Type: field.TypeString},
		{Name: "best_before", Type: field.TypeTime},
		{Name: "use_by", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// IngredientsTable holds the schema information for the "ingredients" table.
	IngredientsTable = &schema.Table{
		Name:        "ingredients",
		Columns:     IngredientsColumns,
		PrimaryKey:  []*schema.Column{IngredientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RecipesColumns holds the columns for the "recipes" table.
	RecipesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "title", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RecipesTable holds the schema information for the "recipes" table.
	RecipesTable = &schema.Table{
		Name:        "recipes",
		Columns:     RecipesColumns,
		PrimaryKey:  []*schema.Column{RecipesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RecipeIngredientsColumns holds the columns for the "recipe_ingredients" table.
	RecipeIngredientsColumns = []*schema.Column{
		{Name: "recipe_id", Type: field.TypeInt},
		{Name: "ingredient_id", Type: field.TypeInt},
	}
	// RecipeIngredientsTable holds the schema information for the "recipe_ingredients" table.
	RecipeIngredientsTable = &schema.Table{
		Name:       "recipe_ingredients",
		Columns:    RecipeIngredientsColumns,
		PrimaryKey: []*schema.Column{RecipeIngredientsColumns[0], RecipeIngredientsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "recipe_ingredients_recipe_id",
				Columns: []*schema.Column{RecipeIngredientsColumns[0]},

				RefColumns: []*schema.Column{RecipesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "recipe_ingredients_ingredient_id",
				Columns: []*schema.Column{RecipeIngredientsColumns[1]},

				RefColumns: []*schema.Column{IngredientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IngredientsTable,
		RecipesTable,
		RecipeIngredientsTable,
	}
)

func init() {
	RecipeIngredientsTable.ForeignKeys[0].RefTable = RecipesTable
	RecipeIngredientsTable.ForeignKeys[1].RefTable = IngredientsTable
}
