// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Ingredient is the predicate function for ingredient builders.
type Ingredient func(*sql.Selector)

// Recipe is the predicate function for recipe builders.
type Recipe func(*sql.Selector)
