// Code generated by entc, DO NOT EDIT.

package ingredient

import (
	"time"

	"github.com/prasetyowira/loadsmile/internal/app/loadsmile-app/lunch/lunchadapter/ent/schema"
)

const (
	// Label holds the string label denoting the ingredient type in the database.
	Label = "ingredient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid vertex property in the database.
	FieldUID = "uid"
	// FieldTitle holds the string denoting the title vertex property in the database.
	FieldTitle = "title"
	// FieldBestBefore holds the string denoting the best_before vertex property in the database.
	FieldBestBefore = "best_before"
	// FieldUseBy holds the string denoting the use_by vertex property in the database.
	FieldUseBy = "use_by"
	// FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at"

	// Table holds the table name of the ingredient in the database.
	Table = "ingredients"
	// RecipesTable is the table the holds the recipes relation/edge. The primary key declared below.
	RecipesTable = "recipe_ingredients"
	// RecipesInverseTable is the table name for the Recipe entity.
	// It exists in this package in order to avoid circular dependency with the "recipe" package.
	RecipesInverseTable = "recipes"
)

// Columns holds all SQL columns for ingredient fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldTitle,
	FieldBestBefore,
	FieldUseBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// RecipesPrimaryKey and RecipesColumn2 are the table columns denoting the
	// primary key for the recipes relation (M2M).
	RecipesPrimaryKey = []string{"recipe_id", "ingredient_id"}
)

var (
	fields = schema.Ingredient{}.Fields()

	// descUID is the schema descriptor for uid field.
	descUID = fields[0].Descriptor()
	// UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	UIDValidator = func() func(string) error {
		validators := descUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(uid string) error {
			for _, fn := range fns {
				if err := fn(uid); err != nil {
					return err
				}
			}
			return nil
		}
	}()

	// descCreatedAt is the schema descriptor for created_at field.
	descCreatedAt = fields[4].Descriptor()
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt = descCreatedAt.Default.(func() time.Time)

	// descUpdatedAt is the schema descriptor for updated_at field.
	descUpdatedAt = fields[5].Descriptor()
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt = descUpdatedAt.Default.(func() time.Time)
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt = descUpdatedAt.UpdateDefault.(func() time.Time)
)
