// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/prasetyowira/loadsmile/internal/app/loadsmile-app/lunch/lunchadapter/ent/predicate"
	"github.com/prasetyowira/loadsmile/internal/app/loadsmile-app/lunch/lunchadapter/ent/recipe"
)

// RecipeDelete is the builder for deleting a Recipe entity.
type RecipeDelete struct {
	config
	predicates []predicate.Recipe
}

// Where adds a new predicate to the delete builder.
func (rd *RecipeDelete) Where(ps ...predicate.Recipe) *RecipeDelete {
	rd.predicates = append(rd.predicates, ps...)
	return rd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rd *RecipeDelete) Exec(ctx context.Context) (int, error) {
	return rd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (rd *RecipeDelete) ExecX(ctx context.Context) int {
	n, err := rd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rd *RecipeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: recipe.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: recipe.FieldID,
			},
		},
	}
	if ps := rd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rd.driver, _spec)
}

// RecipeDeleteOne is the builder for deleting a single Recipe entity.
type RecipeDeleteOne struct {
	rd *RecipeDelete
}

// Exec executes the deletion query.
func (rdo *RecipeDeleteOne) Exec(ctx context.Context) error {
	n, err := rdo.rd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recipe.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rdo *RecipeDeleteOne) ExecX(ctx context.Context) {
	rdo.rd.ExecX(ctx)
}
