/*
 * Lunch API
 *
 * Manage Lunch
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type RecipeList struct {

	Recipes []Recipe `json:"recipes,omitempty"`
}
